[technote]
id = "CTN-008"
series_id = "CTN"
canonical_url = "https://ctn-008.lsst.io"
github_url = "https://github.com/lsst/ctn-008"
github_default_branch = "main"
date_created = 2026-03-27T12:42:31Z
organization.name = "NSF-DOE Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Yousuke"
name.family = "Utsumi"
internal_id = "utsumiy"
orcid = "https://orcid.org/0000-0001-6161-8988"
[[technote.authors.affiliations]]
name = "National Astronomical Observatory of Japan"
internal_id = "NAOJ-Chile"
address = "Santiago"
